//! Who made each file in a project's artifacts, for the Files tab.
//!
//! - A file a bot wrote or edited with its file tools is the first such
//!   bot's, by its transcript.
//! - Otherwise, a file named in a command is the bot whose command first
//!   mentioned its path (a build, a copy, an image render).
//! - `uploads/` holds what the owner attached from the app.
//! - `peers/<machine>/<message>/` holds files a bot on another machine sent
//!   with a result, which the message traces to that bot.

use std::collections::HashMap;

use bus::{Bot, Project};
use chrono::{DateTime, Utc};
use serde::Serialize;

use crate::app::AppState;
use crate::db::Db;

use super::files::Artifact;
use super::writes::Touch;

#[derive(Debug, Clone, Serialize)]
pub struct Creator {
    /// The bot, or `None` for the owner.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bot_id: Option<String>,
    pub name: String,
    /// The bot's avatar; empty for the owner.
    pub avatar: String,
    /// The peer the bot runs on, for one on another machine.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub machine: Option<String>,
    /// How: `wrote`, `edited`, `command`, `upload` or `sent`.
    pub via: &'static str,
}

fn bot_creator(app: &AppState, bot: &Bot, via: &'static str) -> Creator {
    let machine = bot
        .peer_id
        .as_deref()
        .and_then(|peer| app.db.get_peer(peer).ok().flatten())
        .map(|peer| Db::display_peer_name(&peer));
    Creator {
        bot_id: Some(bot.id.clone()),
        name: Db::display_name(bot),
        avatar: bot.avatar.clone(),
        machine,
        via,
    }
}

/// Fills in `created_by` wherever it can be told.
pub fn attribute(app: &AppState, project: &Project, artifacts: &mut [Artifact]) {
    let mut earliest: HashMap<usize, (DateTime<Utc>, Creator)> = HashMap::new();
    // Archived bots made files too, and their transcripts are still there.
    let bots = app
        .db
        .list_bots_with_archived(Some(&project.id))
        .unwrap_or_default();
    for bot in bots.iter().filter(|b| !b.is_linked()) {
        let found = app.chat.with_logs(app, bot, |commands, writes| {
            artifacts
                .iter()
                .enumerate()
                .filter_map(|(i, artifact)| {
                    let touched = writes.first(&artifact.path).map(|(at, touch)| {
                        let via = if touch == Touch::Wrote {
                            "wrote"
                        } else {
                            "edited"
                        };
                        (at, via)
                    });
                    let found = touched.or_else(|| {
                        mentions(&artifact.path, &artifact.rel)
                            .iter()
                            .find_map(|needle| commands.first_mention(needle))
                            .map(|at| (at, "command"))
                    });
                    found.map(|(at, via)| (i, at, via))
                })
                .collect::<Vec<_>>()
        });
        let Ok(found) = found else {
            continue;
        };
        // A file tool beats a command that only mentioned the path; then the
        // earliest wins.
        let rank = |via: &str, at: DateTime<Utc>| (via == "command", at);
        for (i, at, via) in found {
            let better = earliest
                .get(&i)
                .is_none_or(|(seen, creator)| rank(via, at) < rank(creator.via, *seen));
            if better {
                earliest.insert(i, (at, bot_creator(app, bot, via)));
            }
        }
    }
    for (i, artifact) in artifacts.iter_mut().enumerate() {
        artifact.created_by = earliest
            .remove(&i)
            .map(|(_, creator)| creator)
            .or_else(|| by_place(app, &artifact.rel));
    }
    by_task(artifacts);
}

/// The task id a file is named after (`<uuid>-…` or `<8 hex>-…`), which
/// bots put first so a task's files sort together.
fn task_prefix(rel: &str) -> Option<&str> {
    let hex = |s: &str| s.chars().all(|c| c.is_ascii_hexdigit());
    let uuid = rel
        .get(..36)
        .filter(|p| p.split('-').map(str::len).eq([8, 4, 4, 4, 12]) && hex(&p.replace('-', "")));
    uuid.or_else(|| {
        rel.get(..9)
            .filter(|p| p.ends_with('-') && hex(&p[..8]))
            .map(|p| &p[..8])
    })
}

/// A file still unaccounted for, named after a task whose other files have a
/// maker, was generated by that maker's work (a script it wrote, run).
fn by_task(artifacts: &mut [Artifact]) {
    let mut makers: HashMap<String, Creator> = HashMap::new();
    for artifact in artifacts.iter() {
        if let (Some(task), Some(creator)) = (task_prefix(&artifact.rel), &artifact.created_by) {
            if creator.bot_id.is_some() {
                makers
                    .entry(task.to_string())
                    .or_insert_with(|| creator.clone());
            }
        }
    }
    for artifact in artifacts.iter_mut().filter(|a| a.created_by.is_none()) {
        if let Some(maker) = task_prefix(&artifact.rel).and_then(|task| makers.get(task)) {
            artifact.created_by = Some(Creator {
                via: "command",
                ..maker.clone()
            });
        }
    }
}

/// Shortest relative path matched without the artifacts directory before it:
/// bots name artifacts after their task, but a short generic name could be
/// any file a command touched.
const MIN_BARE_NAME: usize = 12;

/// What a command that made a file would contain, most certain first: its
/// full path; its path inside the artifacts directory, which bots reach
/// through a variable (`cp out.csv $A/run-42.csv`); for a file in a folder,
/// the folder (`cp *.png $A/frames-42/`).
fn mentions(path: &str, rel: &str) -> Vec<String> {
    let mut needles = vec![path.to_string()];
    if rel.len() >= MIN_BARE_NAME {
        needles.push(format!("/{rel}"));
    }
    if let Some((folder, _)) = rel.rsplit_once('/') {
        if folder.len() >= MIN_BARE_NAME
            && !matches!(folder, "uploads")
            && !folder.starts_with("peers")
        {
            needles.push(format!("/{folder}/"));
            needles.push(format!("/{folder} "));
        }
    }
    needles
}

/// Files whose folder says who made them: uploads, and a peer's results.
fn by_place(app: &AppState, rel: &str) -> Option<Creator> {
    let mut parts = rel.split('/');
    match parts.next()? {
        "uploads" => Some(Creator {
            bot_id: None,
            name: "you".to_string(),
            avatar: String::new(),
            machine: None,
            via: "upload",
        }),
        "peers" => {
            let (machine, message) = (parts.next()?, parts.next()?);
            let peer = app
                .db
                .list_peers()
                .ok()?
                .into_iter()
                .find(|p| bus::names::dir_name(&p.name) == machine)?;
            let local = app.db.local_message_by_prefix(&peer.id, message).ok()??;
            let sender = app.db.get_message(&local).ok()??.sender.bot_id?;
            let bot = app.db.get_bot(&sender).ok()??;
            Some(bot_creator(app, &bot, "sent"))
        }
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_command_is_matched_by_path_then_by_distinct_name_then_by_folder() {
        assert_eq!(
            mentions("/a/artifacts/report.md", "report.md"),
            vec!["/a/artifacts/report.md"]
        );
        assert_eq!(
            mentions("/a/artifacts/31620468-vtrig.csv", "31620468-vtrig.csv"),
            vec!["/a/artifacts/31620468-vtrig.csv", "/31620468-vtrig.csv"]
        );
        let nested = mentions(
            "/a/artifacts/b8b97477-frames/on.png",
            "b8b97477-frames/on.png",
        );
        assert!(nested.contains(&"/b8b97477-frames/".to_string()));
    }

    #[test]
    fn files_are_grouped_by_the_task_they_are_named_after() {
        assert_eq!(
            task_prefix("e7fddbc6-d590-48c6-9955-5773b5c5b129-summary.json"),
            Some("e7fddbc6-d590-48c6-9955-5773b5c5b129")
        );
        assert_eq!(task_prefix("b8b97477-frames/on.png"), Some("b8b97477"));
        assert_eq!(task_prefix("report.md"), None);
        assert_eq!(task_prefix("weekly-notes.md"), None);
    }
}
