//! `hermesd migrate-home`: moves a pre-rename `~/.gravity` to `~/.thehermes`.
//!
//! Steps, each recorded in `migrate-home.json` inside the home so a failed run
//! resumes where it stopped and `--rollback` can reverse what was done:
//!
//! 1. **Backup** the database, config and transcript dirs into
//!    `backups/pre-rename-<ts>`.
//! 2. **Move** the home directory.
//! 3. **Rename** the daemon's own files (`gravityd.toml` → `hermesd.toml`, …).
//! 4. **Rewrite** home paths in the database, in one transaction, and set
//!    `meta.home_migrated`; then in `hermesd.toml` and the files in the home
//!    its `claude_args` name (`bot-settings.json`).
//! 5. **Rename** Claude Code's transcript and memory dirs, keyed by the
//!    mangled workspace path, so every bot keeps `--continue`, chat history
//!    and its auto-memory.
//! 6. **Link** the old path to the new home for one release.
//! 7. **Repair** git worktrees that recorded the old path.
//!
//! Bot configs (`system.md`, `mcp.json`, hook settings, workspace trust) are
//! regenerated by the daemon itself: `system.md` for every bot at boot, the
//! rest at each bot's start, all from the rewritten database.
//!
//! The daemon must be stopped: `service install` stops the old agent first,
//! and the migration checks both lock files before it moves anything.

mod disk;
#[cfg(test)]
mod env_home_tests;
mod files;
mod preflight;
#[cfg(test)]
pub(crate) mod resume_tests;
mod rollback;
#[cfg(test)]
mod settings_tests;
mod sql;
mod state;
mod steps;
#[cfg(test)]
pub(crate) mod tests;

use std::io::Write;
use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::{bail, Context};

pub use preflight::{blockers_before_stop, dry_run};
use preflight::{daemon_stopped, preflight};
pub use rollback::rollback;
pub use state::{Action, State, Step, STATE_FILE};

use crate::config::Config;

/// What to migrate: the old home, the new one, and the user home whose
/// `~/.claude/projects` holds the transcripts.
#[derive(Debug, Clone)]
pub struct Plan {
    pub from: PathBuf,
    pub to: PathBuf,
    pub user_home: PathBuf,
}

impl Plan {
    pub fn new(from: PathBuf, to: PathBuf, user_home: PathBuf) -> Self {
        Self {
            from,
            to,
            user_home,
        }
    }

    /// The default move for `cfg`: `~/.gravity` to the configured home.
    pub fn default_for(cfg: &Config) -> Self {
        Self::new(
            cfg.user_home.join(crate::brand::LEGACY_HOME_DIR_NAME),
            cfg.home.clone(),
            cfg.user_home.clone(),
        )
    }

    /// `(from, to)` spellings of the home: as given, and as resolved through
    /// symlinks when that differs (macOS `/var` is `/private/var`).
    pub fn path_pairs(&self) -> Vec<(String, String)> {
        let given = (
            self.from.to_string_lossy().into_owned(),
            self.to.to_string_lossy().into_owned(),
        );
        let mut pairs = vec![given.clone()];
        let resolve = |path: &Path| -> Option<PathBuf> {
            let parent = path.parent()?.canonicalize().ok()?;
            Some(parent.join(path.file_name()?))
        };
        if let (Some(from), Some(to)) = (resolve(&self.from), resolve(&self.to)) {
            let resolved = (
                from.to_string_lossy().into_owned(),
                to.to_string_lossy().into_owned(),
            );
            if resolved != given {
                pairs.push(resolved);
            }
        }
        // Git Bash and MSYS tools (and agents using them) write `/c/Users/…`.
        if cfg!(windows) {
            let msys: Vec<_> = pairs
                .iter()
                .filter_map(|(from, to)| Some((sql::msys_spelling(from)?, sql::msys_spelling(to)?)))
                .collect();
            pairs.extend(msys);
        }
        pairs
    }

    fn reversed(&self) -> Vec<(String, String)> {
        self.path_pairs().into_iter().map(|(a, b)| (b, a)).collect()
    }

    fn source_is_real_home(&self) -> bool {
        self.from
            .symlink_metadata()
            .map(|m| m.is_dir() && !m.file_type().is_symlink())
            .unwrap_or(false)
            && self.from.join("bus.sqlite").is_file()
    }

    /// The run in progress, if any. A crash between moving the home and
    /// saving the state leaves a log in the new home that does not know about
    /// the move yet; that move is recorded here, so resume and rollback both
    /// see it. Callers that change anything save the state themselves.
    pub(crate) fn state(&self) -> anyhow::Result<Option<State>> {
        let Some(path) = State::locate(&self.from, &self.to) else {
            return Ok(None);
        };
        let mut state = State::load(&path)?;
        let moved_unrecorded = path.starts_with(&self.to)
            && state.from == self.from
            && !state.done(Step::Move)
            && self.from.symlink_metadata().is_err();
        if moved_unrecorded {
            note_move(self, &mut state);
        }
        Ok(Some(state))
    }
}

/// Records a finished home move: the step, where the backup went with it,
/// and the rename rollback undoes. The state file moved with the home, so
/// this only happens once it has.
fn note_move(plan: &Plan, state: &mut State) {
    state.steps.push(Step::Move);
    if let Some(backup) = state.backup.take() {
        state.backup = backup
            .strip_prefix(&plan.from)
            .map(|rest| plan.to.join(rest))
            .ok()
            .or(Some(backup));
    }
    state.actions.push(Action::Rename {
        from: plan.from.clone(),
        to: plan.to.clone(),
    });
}

/// Where a test makes the run stop dead, as if the process were killed:
/// nothing after it runs and nothing more is saved.
fn crash_point(_at: &str) -> anyhow::Result<()> {
    #[cfg(test)]
    if resume_tests::CRASH_AT.with(|at| at.borrow().as_deref() == Some(_at)) {
        bail!("injected crash at {_at}");
    }
    Ok(())
}

/// The migration the default home still needs, if any: a real `~/.gravity`
/// holding a database, or a run that stopped partway. A home chosen with
/// `THEHERMES_HOME` is the user's to migrate (`migrate-home --from --to`).
pub fn pending(cfg: &Config) -> anyhow::Result<Option<Plan>> {
    pending_unless(cfg, crate::config::home_is_overridden())
}

/// [`pending`] with the override already decided.
pub(crate) fn pending_unless(cfg: &Config, overridden: bool) -> anyhow::Result<Option<Plan>> {
    if overridden {
        return Ok(None);
    }
    pending_for(&Plan::default_for(cfg))
}

/// `plan`, when it still has work to do.
pub fn pending_for(plan: &Plan) -> anyhow::Result<Option<Plan>> {
    if let Some(state) = plan.state()? {
        return Ok((!state.is_complete()).then(|| plan.clone()));
    }
    Ok(plan.source_is_real_home().then(|| plan.clone()))
}

/// Refuses to start a daemon on an empty new home while the old one still
/// holds the data: it would come up with no bots, and the next migration
/// would find the destination taken.
pub fn refuse_unmigrated(cfg: &Config) -> anyhow::Result<()> {
    if let Some(plan) = pending(cfg)? {
        bail!(
            "{} has not been migrated to {}; run `hermesd migrate-home` \
             (or `hermesd service install`, which runs it) first",
            plan.from.display(),
            plan.to.display()
        );
    }
    Ok(())
}

/// Runs (or resumes) the migration. Idempotent: completed steps are skipped.
pub fn run(plan: &Plan, out: &mut dyn Write) -> anyhow::Result<State> {
    let mut state = match plan.state()? {
        Some(state) => state,
        None => State::new(&plan.from, &plan.to),
    };
    if state.is_complete() {
        writeln!(out, "already migrated to {}", plan.to.display())?;
        return Ok(state);
    }
    let blockers = preflight(plan, Some(&state));
    if !blockers.is_empty() {
        bail!("cannot migrate: {}", blockers.join("; "));
    }
    let home = if state.done(Step::Move) {
        &plan.to
    } else {
        &plan.from
    };
    daemon_stopped(home, Duration::from_secs(30)).context("the daemon is still running")?;
    #[cfg(windows)]
    if !state.done(Step::Move) {
        disk::probe_move(&plan.from)?;
    }
    state.save()?;
    for step in Step::ALL {
        if state.done(step) {
            continue;
        }
        writeln!(out, "{step:?}...")?;
        run_step(plan, &mut state, step).with_context(|| format!("step {step:?}"))?;
        crash_point(&format!("{step:?}"))?;
        state.finish_step(step)?;
    }
    state.completed_at = Some(chrono::Utc::now().to_rfc3339());
    state.save()?;
    for warning in &state.warnings {
        writeln!(out, "warning: {warning}")?;
    }
    writeln!(out, "migrated to {}", plan.to.display())?;
    Ok(state)
}

fn run_step(plan: &Plan, state: &mut State, step: Step) -> anyhow::Result<()> {
    match step {
        Step::Backup => {
            steps::backup(plan, state)?;
        }
        Step::Move => {
            // An empty destination (made by hand, or by a daemon that was
            // refused) is not data; preflight refused a non-empty one.
            if plan.to.is_dir() {
                std::fs::remove_dir(&plan.to)?;
            }
            if let Some(parent) = plan.to.parent() {
                std::fs::create_dir_all(parent)?;
            }
            // The state file moves with the home; record the step's action
            // only once it has. A crash in between is caught by `Plan::state`.
            steps::move_home(&plan.from, &plan.to).with_context(|| {
                format!("moving {} to {}", plan.from.display(), plan.to.display())
            })?;
            crash_point("moved")?;
            note_move(plan, state);
            state.save()?;
        }
        Step::RenameFiles => {
            for (old, new) in steps::renamed_files() {
                let (old, new) = (plan.to.join(old), plan.to.join(new));
                if old.exists() && !new.exists() {
                    steps::rename(state, &old, &new)?;
                }
            }
        }
        Step::Database => {
            let db = plan.to.join("bus.sqlite");
            let pairs = plan.path_pairs();
            // Logged before it runs: the reverse rewrite is harmless if this
            // never committed, and a crash right after it is still undone.
            if !state
                .actions
                .iter()
                .any(|a| matches!(a, Action::Database { .. }))
            {
                state.record(Action::Database {
                    from: pairs[0].0.clone(),
                    to: pairs[0].1.clone(),
                })?;
            }
            sql::apply(&db, &pairs, true)?;
            files::rewrite(plan, state)?;
        }
        Step::Transcripts => {
            steps::move_transcripts(plan, state)?;
        }
        Step::Symlink => steps::symlink(plan, state)?,
        Step::Worktrees => {
            steps::repair_worktrees(plan, state);
        }
    }
    Ok(())
}

/// Whether the database in `home` records a finished migration.
pub fn is_migrated(home: &Path) -> bool {
    sql::is_marked(&home.join("bus.sqlite")).unwrap_or(false)
}
