//! `hermesd migrate-home`: moves a pre-rename `~/.gravity` to `~/.thehermes`.
//!
//! Steps, each recorded in `migrate-home.json` inside the home so a failed run
//! resumes where it stopped and `--rollback` can reverse what was done:
//!
//! 1. **Backup** the database, config and transcript dirs into
//!    `backups/pre-rename-<ts>`.
//! 2. **Move** the home directory.
//! 3. **Rename** the daemon's own files (`gravityd.toml` → `hermesd.toml`, …).
//! 4. **Rewrite** home paths in the database, in one transaction, and set
//!    `meta.home_migrated`.
//! 5. **Rename** Claude Code's transcript and memory dirs, keyed by the
//!    mangled workspace path, so every bot keeps `--continue`, chat history
//!    and its auto-memory.
//! 6. **Link** the old path to the new home for one release.
//! 7. **Repair** git worktrees that recorded the old path.
//!
//! Bot configs (`system.md`, `mcp.json`, hook settings, workspace trust) are
//! regenerated by the daemon itself: `system.md` for every bot at boot, the
//! rest at each bot's start, all from the rewritten database.
//!
//! The daemon must be stopped: `service install` stops the old agent first,
//! and the migration checks both lock files before it moves anything.

mod rollback;
mod sql;
mod state;
mod steps;
#[cfg(test)]
mod tests;

use std::io::Write;
use std::path::{Path, PathBuf};
use std::time::{Duration, Instant};

use anyhow::{bail, Context};

pub use rollback::rollback;
pub use state::{Action, State, Step, STATE_FILE};

use crate::config::Config;

/// Space kept free beyond the backup itself.
const DISK_MARGIN: u64 = 512 * 1024 * 1024;

/// What to migrate: the old home, the new one, and the user home whose
/// `~/.claude/projects` holds the transcripts.
#[derive(Debug, Clone)]
pub struct Plan {
    pub from: PathBuf,
    pub to: PathBuf,
    pub user_home: PathBuf,
}

impl Plan {
    pub fn new(from: PathBuf, to: PathBuf, user_home: PathBuf) -> Self {
        Self {
            from,
            to,
            user_home,
        }
    }

    /// The default move for `cfg`: `~/.gravity` to the configured home.
    pub fn default_for(cfg: &Config) -> Self {
        Self::new(
            cfg.user_home.join(crate::brand::LEGACY_HOME_DIR_NAME),
            cfg.home.clone(),
            cfg.user_home.clone(),
        )
    }

    /// `(from, to)` spellings of the home: as given, and as resolved through
    /// symlinks when that differs (macOS `/var` is `/private/var`).
    pub fn path_pairs(&self) -> Vec<(String, String)> {
        let given = (
            self.from.to_string_lossy().into_owned(),
            self.to.to_string_lossy().into_owned(),
        );
        let mut pairs = vec![given.clone()];
        let resolve = |path: &Path| -> Option<PathBuf> {
            let parent = path.parent()?.canonicalize().ok()?;
            Some(parent.join(path.file_name()?))
        };
        if let (Some(from), Some(to)) = (resolve(&self.from), resolve(&self.to)) {
            let resolved = (
                from.to_string_lossy().into_owned(),
                to.to_string_lossy().into_owned(),
            );
            if resolved != given {
                pairs.push(resolved);
            }
        }
        pairs
    }

    fn reversed(&self) -> Vec<(String, String)> {
        self.path_pairs().into_iter().map(|(a, b)| (b, a)).collect()
    }

    fn source_is_real_home(&self) -> bool {
        self.from
            .symlink_metadata()
            .map(|m| m.is_dir() && !m.file_type().is_symlink())
            .unwrap_or(false)
            && self.from.join("bus.sqlite").is_file()
    }

    fn state(&self) -> anyhow::Result<Option<State>> {
        State::locate(&self.from, &self.to)
            .map(|path| State::load(&path))
            .transpose()
    }
}

/// The migration the default home still needs, if any: a real `~/.gravity`
/// holding a database, or a run that stopped partway. A home chosen with
/// `THEHERMES_HOME` is the user's to migrate (`migrate-home --from --to`).
pub fn pending(cfg: &Config) -> anyhow::Result<Option<Plan>> {
    if crate::config::home_is_overridden() {
        return Ok(None);
    }
    pending_for(&Plan::default_for(cfg))
}

/// `plan`, when it still has work to do.
pub fn pending_for(plan: &Plan) -> anyhow::Result<Option<Plan>> {
    if let Some(state) = plan.state()? {
        return Ok((!state.is_complete()).then(|| plan.clone()));
    }
    Ok(plan.source_is_real_home().then(|| plan.clone()))
}

/// Refuses to start a daemon on an empty new home while the old one still
/// holds the data: it would come up with no bots, and the next migration
/// would find the destination taken.
pub fn refuse_unmigrated(cfg: &Config) -> anyhow::Result<()> {
    if let Some(plan) = pending(cfg)? {
        bail!(
            "{} has not been migrated to {}; run `hermesd migrate-home` \
             (or `hermesd service install`, which runs it) first",
            plan.from.display(),
            plan.to.display()
        );
    }
    Ok(())
}

/// Everything a run would touch, and anything that would stop it.
pub fn dry_run(plan: &Plan, out: &mut dyn Write) -> anyhow::Result<bool> {
    let state = plan.state()?;
    let mut blockers = preflight(plan, state.as_ref());
    writeln!(
        out,
        "migrate {} -> {}",
        plan.from.display(),
        plan.to.display()
    )?;
    if let Some(state) = &state {
        writeln!(out, "resuming; done so far: {:?}", state.steps)?;
    }
    let home = if state.as_ref().is_some_and(|s| s.done(Step::Move)) {
        &plan.to
    } else {
        &plan.from
    };
    for (old, new) in steps::renamed_files() {
        if home.join(&old).exists() {
            writeln!(out, "rename    {} -> {}", old.display(), new.display())?;
        }
    }
    let db = home.join("bus.sqlite");
    if db.is_file() {
        for (column, rows) in sql::count(&db, &plan.path_pairs())? {
            writeln!(out, "rewrite   {column}: {rows} row(s)")?;
        }
    }
    let transcripts = steps::transcript_dirs(plan)?;
    let mut needed = steps::tree_size(&db) + DISK_MARGIN;
    for (old, new) in &transcripts {
        needed += steps::tree_size(old);
        writeln!(out, "rename    {} -> {}", old.display(), new.display())?;
    }
    writeln!(
        out,
        "link      {} -> {}",
        plan.from.display(),
        plan.to.display()
    )?;
    match steps::free_bytes(home) {
        Some(free) => {
            writeln!(
                out,
                "disk      {} MB free, {} MB needed",
                free >> 20,
                needed >> 20
            )?;
            if free < needed && !state.as_ref().is_some_and(|s| s.done(Step::Backup)) {
                blockers.push(format!(
                    "not enough free disk for the backup ({} MB)",
                    needed >> 20
                ));
            }
        }
        None => writeln!(
            out,
            "disk      free space unknown; backup needs {} MB",
            needed >> 20
        )?,
    }
    for blocker in &blockers {
        writeln!(out, "blocked   {blocker}")?;
    }
    Ok(blockers.is_empty())
}

/// Reasons a run cannot start or resume.
fn preflight(plan: &Plan, state: Option<&State>) -> Vec<String> {
    let mut blockers = Vec::new();
    if state.is_some_and(State::is_complete) {
        blockers.push("already migrated".to_string());
        return blockers;
    }
    let moved = state.is_some_and(|s| s.done(Step::Move));
    if !moved {
        if !plan.source_is_real_home() {
            blockers.push(format!("{} holds no daemon home", plan.from.display()));
        }
        if let Ok(mut entries) = std::fs::read_dir(&plan.to) {
            if entries.next().is_some() {
                blockers.push(format!("{} exists and is not empty", plan.to.display()));
            }
        }
    }
    let home = if moved { &plan.to } else { &plan.from };
    if home.exists() && daemon_stopped(home, Duration::ZERO).is_err() {
        blockers.push(format!("a daemon is running against {}", home.display()));
    }
    blockers
}

/// Waits up to `wait` for both the old and the new daemon to let go of
/// `home`. The locks are released again before anything moves.
fn daemon_stopped(home: &Path, wait: Duration) -> anyhow::Result<()> {
    let deadline = Instant::now() + wait;
    loop {
        // `lock` claims both the old and the new lock file.
        let held = crate::home::lock(home).map(drop);
        match held {
            Ok(()) => return Ok(()),
            Err(error) if Instant::now() >= deadline => return Err(error),
            Err(_) => std::thread::sleep(Duration::from_millis(200)),
        }
    }
}

/// Runs (or resumes) the migration. Idempotent: completed steps are skipped.
pub fn run(plan: &Plan, out: &mut dyn Write) -> anyhow::Result<State> {
    let mut state = match plan.state()? {
        Some(state) => state,
        None => State::new(&plan.from, &plan.to),
    };
    if state.is_complete() {
        writeln!(out, "already migrated to {}", plan.to.display())?;
        return Ok(state);
    }
    let blockers = preflight(plan, Some(&state));
    if !blockers.is_empty() {
        bail!("cannot migrate: {}", blockers.join("; "));
    }
    let home = if state.done(Step::Move) {
        &plan.to
    } else {
        &plan.from
    };
    daemon_stopped(home, Duration::from_secs(30)).context("the daemon is still running")?;
    state.save()?;
    for step in Step::ALL {
        if state.done(step) {
            continue;
        }
        writeln!(out, "{step:?}...")?;
        run_step(plan, &mut state, step).with_context(|| format!("step {step:?}"))?;
        state.finish_step(step)?;
    }
    state.completed_at = Some(chrono::Utc::now().to_rfc3339());
    state.save()?;
    for warning in &state.warnings {
        writeln!(out, "warning: {warning}")?;
    }
    writeln!(out, "migrated to {}", plan.to.display())?;
    Ok(state)
}

fn run_step(plan: &Plan, state: &mut State, step: Step) -> anyhow::Result<()> {
    match step {
        Step::Backup => {
            steps::backup(plan, state)?;
        }
        Step::Move => {
            // An empty destination (made by hand, or by a daemon that was
            // refused) is not data; preflight refused a non-empty one.
            if plan.to.is_dir() {
                std::fs::remove_dir(&plan.to)?;
            }
            if let Some(parent) = plan.to.parent() {
                std::fs::create_dir_all(parent)?;
            }
            // The state file moves with the home; record the step's action
            // only once it has.
            std::fs::rename(&plan.from, &plan.to).with_context(|| {
                format!("moving {} to {}", plan.from.display(), plan.to.display())
            })?;
            state.steps.push(Step::Move);
            if let Some(backup) = state.backup.take() {
                state.backup = backup
                    .strip_prefix(&plan.from)
                    .map(|rest| plan.to.join(rest))
                    .ok()
                    .or(Some(backup));
            }
            state.record(Action::Rename {
                from: plan.from.clone(),
                to: plan.to.clone(),
            })?;
        }
        Step::RenameFiles => {
            for (old, new) in steps::renamed_files() {
                let (old, new) = (plan.to.join(old), plan.to.join(new));
                if old.exists() && !new.exists() {
                    steps::rename(state, &old, &new)?;
                }
            }
        }
        Step::Database => {
            let db = plan.to.join("bus.sqlite");
            let pairs = plan.path_pairs();
            sql::apply(&db, &pairs, true)?;
            state.record(Action::Database {
                from: pairs[0].0.clone(),
                to: pairs[0].1.clone(),
            })?;
        }
        Step::Transcripts => {
            steps::move_transcripts(plan, state)?;
        }
        Step::Symlink => steps::symlink(plan, state)?,
        Step::Worktrees => {
            steps::repair_worktrees(plan, state);
        }
    }
    Ok(())
}

/// Whether the database in `home` records a finished migration.
pub fn is_migrated(home: &Path) -> bool {
    sql::is_marked(&home.join("bus.sqlite")).unwrap_or(false)
}
