#!/bin/bash
set -euo pipefail

# Local development run: a workspace-private hermesd plus the desktop frontend.
#
#   scripts/dev.sh          the real Tauri window against a private daemon
#   scripts/dev.sh web      frontend in the browser (Vite) — fastest loop
#
# Nothing here touches ~/.gravity: the daemon gets its own home under
# .dev/gravityd/ and its own port, so several Conductor workspaces (and the
# installed production daemon) can run side by side.
#
# Ports come from CONDUCTOR_PORT (Conductor hands each workspace ten):
#   CONDUCTOR_PORT     frontend / Tauri devUrl
#   CONDUCTOR_PORT+1   hermesd HTTP + WebSocket + MCP
#
# GRAVITY_RUNTIME=double swaps the real `claude` CLI for the deterministic echo
# runtime — use it for UI and terminal work that should not spend tokens.

MODE="${1:-app}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

BASE_PORT="${CONDUCTOR_PORT:-1420}"
WEB_PORT="$BASE_PORT"
DAEMON_PORT="$((BASE_PORT + 1))"
RUNTIME="${GRAVITY_RUNTIME:-pty}"

export GRAVITY_HOME="${GRAVITY_HOME:-$ROOT/.dev/gravityd}"
export CONDUCTOR_PORT="$BASE_PORT" # vite.config.ts reads this

mkdir -p "$GRAVITY_HOME"
cat > "$GRAVITY_HOME/gravityd.toml" <<EOF
# Generated by scripts/dev.sh on every run — edit the script, not this file.
home = "$GRAVITY_HOME"
bind = ["127.0.0.1"]
port = $DAEMON_PORT
runtime = "$RUNTIME"
supervision_interval_ms = 1000
EOF

cargo build -p hermesd --manifest-path "$ROOT/Cargo.toml"

# Job control puts each background child in its own process group, so cleanup
# can signal the whole group. `tauri dev` in particular spawns Vite and the app
# binary as grandchildren that outlive their parent otherwise, and a stray Vite
# holds the strict port against the next run.
set -m

"$ROOT/target/debug/hermesd" > "$GRAVITY_HOME/dev.log" 2>&1 &
GRAVITY_PID=$!
CLIENT_PID=""

# Both halves run in the background and the script waits, so a signal from
# Conductor (or Ctrl-C) reaches the trap instead of being deferred until the
# foreground child exits.
kill_group() {
  kill -TERM -- "-$1" 2>/dev/null || kill -TERM "$1" 2>/dev/null || true
}

cleanup() {
  trap - EXIT INT TERM
  if [ -n "$CLIENT_PID" ]; then
    kill_group "$CLIENT_PID"
  fi
  kill_group "$GRAVITY_PID"
  wait 2>/dev/null || true
}
trap cleanup EXIT INT TERM

for _ in $(seq 1 50); do
  if curl -fsS "http://127.0.0.1:$DAEMON_PORT/health" > /dev/null 2>&1; then
    break
  fi
  if ! kill -0 "$GRAVITY_PID" 2>/dev/null; then
    echo "hermesd exited during startup; last log lines:" >&2
    tail -n 20 "$GRAVITY_HOME/dev.log" >&2
    exit 1
  fi
  sleep 0.2
done

TOKEN="$(cat "$GRAVITY_HOME/secrets/client.token" 2>/dev/null || true)"
echo "hermesd  runtime=$RUNTIME port=$DAEMON_PORT home=$GRAVITY_HOME log=$GRAVITY_HOME/dev.log"

# Baked into the bundle by Vite so a fresh client connects to this daemon
# instead of the installed one, and skips the setup wizard.
export VITE_GRAVITY_DEV_PORT="$DAEMON_PORT"
export VITE_GRAVITY_DEV_TOKEN="$TOKEN"

if [ "$MODE" = "app" ]; then
  TRIPLE="$(rustc -vV | sed -n 's/^host: //p')"
  if [ ! -x "$ROOT/apps/desktop/src-tauri/binaries/hermesd-$TRIPLE" ]; then
    "$ROOT/scripts/prepare-sidecar.sh"
  fi
  cd "$ROOT/apps/desktop"
  pnpm tauri dev --config "{\"build\":{\"devUrl\":\"http://localhost:$WEB_PORT\"}}" &
  CLIENT_PID=$!
  wait "$CLIENT_PID"
  exit 0
fi

cat <<EOF

Open http://localhost:$WEB_PORT/ — the page connects to this daemon on its own.
To point it somewhere else, override it from the browser console:

  localStorage.setItem('gravity.connection', JSON.stringify({host:'127.0.0.1',port:$DAEMON_PORT}));
  localStorage.setItem('gravity.device-token', '$TOKEN');
  location.reload();

EOF

cd "$ROOT/apps/desktop"
pnpm dev &
CLIENT_PID=$!
wait "$CLIENT_PID"
